language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - cd ../
  - git clone https://github.com/jpcw/bobbyplugins.jpcw.git
  - cd bobbyplugins.jpcw
  - python setup.py install
  - cd ../mr.bobby
  - python setup.py develop
  - easy_install mr.bobby[test]
script:
  - make test -k
